[package]
name = "simplefi_redis"
# version.workspace = true
# edition.workspace = true
# rust-version.workspace = true
# homepage.workspace = true
# repository.workspace = true
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { workspace = true, features = ["tokio-comp", "connection-manager"]}

[dev-dependencies]
tokio = { workspace = true }