[package]
name = "simplefi-redis"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { workspace = true, features = ["tokio-comp", "connection-manager"]}

[dev-dependencies]
tokio = { workspace = true }