[workspace]

members = [
    "abi_discovery",
    "settings",
    "shared_utils",
    "third_parties",
]

[workspace.dependencies]
async-trait = "0.1"
clap = { version = "4.1", features = ["derive"] }
confy = { version = "0.5.1" }
flate2 = "1.0"
futures = "0.3"
lapin = "2.1.1"
once_cell = "1.17"
hex = "0.4"
http = "0.2"
mongodb = "2.4"
mockito = "1.0"
rand = "0.8"
redis = { version = "0.22", features = ["tokio-comp"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
tonic = "0.8"
tokio = { version = "1", features = ["full"] }

