[package]
name = "protocol_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
mongodb = { workspace = true }



# shared types
mongo_types = { path = "../../types/mongo"}

# shared utils
simplefi_engine_settings = { path = "../../utils/settings"}
simplefi-redis = { path = "../../utils/redis" }
simplefi-chains = { path = "../../utils/chains" }
