[package]
name = "db"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interfaces = { workspace = true }
sip-codecs = { path = "../codecs" }
simp-primitives = { path = "../../primitives" }
rlp = { path = "../../rlp" }
rocksdb = { workspace = true, features = ["multi-threaded-cf"] }
eyre = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
assert_matches = "1.5.0"
page_size = "0.6.0"
serde = { workspace = true }
bytes = { workspace = true }

proptest = { workspace = true }
proptest-derive = { version = "0.4" }
arbitrary = "1.3.0"
modular-bitfield = "0.11.2"
test-fuzz = "4"

parity-scale-codec = { version = "3.2.1", features = ["bytes"] }
postcard = { version = "1.0.2", features = ["alloc"] }