[package]
name = "simp"
version.workspace = true
edition.workspace = true

[dependencies]
simp-primitives = { path = "../../crates/primitives" }
simp-rpc = { path = "../../crates/rpc/rpc" }
simp-rpc-api = { path = "../../crates/rpc/rpc-api", features = ["client"] }
simp-rpc-builder = { path = "../../crates/rpc/rpc-builder" }
simp-tracing.workspace = true
simp-tasks.workspace = true

# misc
aquamarine.workspace = true
clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
thiserror.workspace = true

# metrics
metrics-exporter-prometheus = "0.12.1"
metrics-util = "0.15.0"
metrics-process = "1.0.9"
simp-metrics.workspace = true
metrics.workspace = true

# tracing
tracing.workspace = true

# async
tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }
futures.workspace = true
pin-project.workspace = true

# http/rpc
hyper = "1.2.0"

# crypto
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }

# io
shellexpand = "3.0.0"
dirs-next = "2.0.0"

# test vectors generation
proptest.workspace = true
rand.workspace = true

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }