scrape_configs:
  - job_name: prometheus
    metrics_path: "/metrics"
    scrape_interval: 20s
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: grafana
    metrics_path: "/metrics"
    scrape_interval: 20s
    static_configs:
      - targets: ["host.docker.internal:3000"]
  - job_name: hello
    metrics_path: "/"
    scrape_interval: 5s
    static_configs:
      - targets: ['hello:9001', 'localhost:9001', 'host.docker.internal:9001']
