[package]
name = "simplefi_engine_settings"
version = "0.1.0"
edition = "2021"
# version.workspace = true
# edition.workspace = true
# rust-version.workspace = true
# homepage.workspace = true
# repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ={ workspace = true }
confy ={ workspace = true }
serde ={ workspace = true }
