[package]
name = "simplefi_engine_settings"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
confy ={ workspace = true }
serde ={ workspace = true, features = ["derive"] }
simp-primitives = { workspace = true }