[package]
name = "simplefi-chains"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
ethabi = { workspace = true }
hex = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true }


grpc_server = { path = "../../grpc_server" }

#shared utils
simplefi_engine_settings = { path = "../../utils/settings" }

# shared types
mongo_types = { path = "../../types/mongo" }