{
 "title": "hello",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(up)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hello_network_connected_peers", "legendFormat": "__auto" }
   ]
  },
  { "title": "RPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 236 } },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "The number of active requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hello_rpc_server_requests_started - hello_rpc_server_requests_finished",
     "legendFormat": "Active Requests"
    }
   ]
  },
  {
   "title": "Active Websocket Connections",
   "type": "graph",
   "description": "The number of active websocket connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hello_rpc_server_ws_session_opened - hello_rpc_server_ws_session_closed",
     "legendFormat": "Active Websocket Connections"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "graph",
   "description": "The number of failed calls.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hello_rpc_server_failed_calls[1m])",
     "legendFormat": "Failed Requests"
    }
   ]
  },
  {
   "title": "Request Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
   "targets": [
    {
     "expr": "sum(increase(hello_rpc_server_request_latency[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Call Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
   "targets": [
    {
     "expr": "sum(increase(hello_rpc_server_call_latency[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}