[package]
name = "bronze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true}
parquet = {workspace = true}
chrono = {workspace = true}
log = {workspace = true}
rayon = {workspace = true}
settings = {path = "../settings"}
chains_drivers = {path = "../chains_drivers"}
shared_types = {path = "../shared_types"}
shared_utils = {path = "../shared_utils"}