[package]
name = "abi_discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { workspace = true }
settings = { path = "../settings" }
rand = { workspace = true }
redis = { workspace = true }
third_parties = { path = "../third_parties" }
tokio = { workspace = true, features = ["full"] }
