name: Rust Test on PR
run-name: ${{ github.actor }} is testing out this repository

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  # Clone git repository
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
